package com.example.smd.enums;

public enum PromptKey {
    CLO_GENERATOR,
    VALIDATOR_PROMPT,
    COMPARISON_PROMPT,
    DETERMINE_IMPACT,
    MASTER_DATA_EXTRACTOR_PROMPT,
    PO_PLO_COMPLIANCE_CHECKER_PROMPT,
    PO_PLO_MAPPING_CHECKER_PROMPT,
    CLO_PLO_MAPPING_CHECKER_PROMPT,
    ASSESSMENT_CLO_MAPPING_PROMPT,
    SESSION_CLO_MAPPING_PROMPT,
    VALIDATE_DATA_EXTRACTOR_PROMPT
}
